# ProGuard & R8 Release Build Optimization Rules

-optimizationpasses 5
-dontpreverify
-repackageclasses ''
-allowaccessmodification

# Remove debug attributes and line numbers to shrink APK metadata
-renamesourcefileattribute ""
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod

# Strip all android.util.Log calls in release build
-assumenosideeffects class android.util.Log {
    public static *** v(...);
    public static *** d(...);
    public static *** i(...);
    public static *** w(...);
}

# Preserve Moshi reflection & generated adapters
-keepclassmembers class * {
    @com.squareup.moshi.* <fields>;
}
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}

# Preserve Room Database implementation classes generated by KSP
-keep class * extends androidx.room.RoomDatabase
-dontwarn androidx.room.paging.**

# Keep data layer models to prevent Moshi and Room crashes
-keep class com.aistudio.classroll.jkmxlp.data.** { *; }

# OkHttp & Retrofit optimizations
-dontwarn okhttp3.internal.**
-dontwarn retrofit2.Platform**
-keepclassmembers class retrofit2.Response { *; }

# Kotlin Coroutines optimization (strip debug agent)
-dontwarn kotlinx.coroutines.debug.**

# Optimize Compose UI runtime
-dontwarn androidx.compose.**

